version: '3.4'

services: 
  
  sqlserverService:  
    image: mcr.microsoft.com/mssql/server:2019-latest  
    hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "fake password !1234"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '9433:1433'  
    expose:  
      - 1433